<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_entity_presave().
 */
function revision_log_default_entity_presave(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if (isset($entity->revision_log) && empty($entity->revision_log->getString())) {
      $original = _revision_log_default_get_original($entity);
      // Use the current timestamp if the revision_timestamp is the same as its
      // original value (often happens with custom code, REST, and Quick Edit).
      if (($original && $entity->revision_timestamp->equals($original->revision_timestamp)) || empty($entity->revision_timestamp->getString())) {
        $entity->revision_timestamp = time();
      }
      // The revision UID is not always set correctly, especially when using
      // the API or command line to update entities.
      $entity->revision_uid = \Drupal::currentUser()->id();
      if ($entity->isNew()) {
        $bundle_type = $entity->getEntityType()->getBundleEntityType();
        $bundle = \Drupal::entityTypeManager()
          ->getStorage($bundle_type)
          ->load($entity->bundle());
        $entity->revision_log = t('Created new @bundle', [
          '@bundle' => $bundle->label()
        ]);
      }
      else if ($entity->isNewTranslation()) {
        $entity->revision_log = t('Created @language translation', [
          '@language' => $entity->language()->getName()
        ]);
      }
      else {
        $changed_fields = [];
        $ignore = [
          'changed',
          'revision_log',
          'vid',
          'revision_timestamp',
          'revision_translation_affected',
          'revision_uid',
        ];
        /** @var \Drupal\Core\Entity\ContentEntityInterface $original */
        /** @var \Drupal\Core\Field\FieldItemListInterface $field_items */
        foreach ($entity as $field_name => $field_items) {
          if (in_array($field_name, $ignore, TRUE) || ($field_name === 'path' && !empty($entity->path->pathauto))) {
            continue;
          }
          if (!$original->hasField($field_name) || !$field_items->equals($original->get($field_name))) {
            $changed_fields[] = $field_items->getDataDefinition()->getLabel();
          }
        }
        if (!empty($changed_fields)) {
          if (count($changed_fields) <= 2) {
            $entity->revision_log = \Drupal::translation()->formatPlural(count($changed_fields),'Updated the @fields field', 'Updated the @fields fields', [
              '@fields' => implode(' and ', $changed_fields),
            ]);
          }
          else {
            $last_field = array_pop($changed_fields);
            $entity->revision_log = t('Updated the @fields, and @last_field fields', [
              '@fields' => implode(', ', $changed_fields),
              '@last_field' => $last_field,
            ]);
          }
        }
      }
    }
  }
}

/**
 * Gets the original entity for an entity about to be saved.
 *
 * @param \Drupal\Core\Entity\ContentEntityInterface $entity
 *   The entity that is about to be saved.
 *
 * @return \Drupal\Core\Entity\ContentEntityInterface
 *   The original entity.
 */
function _revision_log_default_get_original(ContentEntityInterface $entity) {
  // If the entity uses Moderation, load the latest revision as the original.
  // @todo File a core issue for this?
  $handler = \Drupal::moduleHandler();
  $is_moderated = FALSE;
  if ($handler->moduleExists('content_moderation')) {
    /** @var \Drupal\content_moderation\ModerationInformation $information */
    $information = \Drupal::service('content_moderation.moderation_information');
    $is_moderated = $information->isModeratedEntity($entity);
  }
  else if ($handler->moduleExists('workbench_moderation')) {
    /** @var \Drupal\workbench_moderation\ModerationInformation $information */
    $information = \Drupal::service('workbench_moderation.moderation_information');
    $is_moderated = $information->isModeratableEntity($entity);
  }
  if ($is_moderated) {
    $latest = $information
      ->getLatestRevision($entity->getEntityTypeId(), $entity->id());
    $langcode = $entity->language()->getId();
    if ($latest && $latest->hasTranslation($langcode)) {
      $original = $latest->getTranslation($langcode);
    }
  }
  return isset($original) ? $original : $entity->original;
}
